# Generated by Django 5.2.3 on 2025-07-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-question', max_length=100),
        ),
    ]
